# Generated by Django 3.1.1 on 2020-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_peliculafavorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='favoritos',
            field=models.IntegerField(default=0),
        ),
    ]
